Forbidden resourced handler
xenit-eu/helm-alfresco pull request #133
Opened 2024-01-18 13:47 UTC by JoostDeCupere

2024-01-18 14:36 UTC, thijslemmens requested changes
I'm not convinced that the current naming and description is clear.

2024-01-18 14:36 UTC, thijslemmens commented on xenit-alfresco/templates/ingress/alfresco-ingress.yaml
> +      {{- end }}
why end and restart if?

2024-01-18 14:42 UTC, JoostDeCupere commented on xenit-alfresco/templates/ingress/alfresco-ingress.yaml
> +      {{- end }}
no reason, removed it

2024-01-18 15:16 UTC, thijslemmens approved these changes
I don't think we need the .enabled but if you disagree you can leave it.

2024-01-18 15:36 UTC, thijslemmens requested changes
so also the wcs and wcservice endpoints need to be handled

2024-01-19 08:55 UTC, thijslemmens approved these changes

2024-01-19 08:57 UTC, hechmi-dammak-xenit approved these changes

2024-01-19 09:25 UTC, merged