Nys2aws-43 refine controls on netpols & cilium netpols
xenit-eu/helm-alfresco pull request #164
Opened 2024-10-10 11:12 UTC by RVanhuysseXenit

cilium netpolls were tied to a 'cni' variable, which was not correct, given that cilium can be chained to other cnis (as is the case for aws)

2024-10-10 11:45 UTC, gert-glassee commented
I do not understand the need for this. Is there a specific need to have cilium network policies disabled when the cni=cilium? or to have them enabled when cni=aws?
In case of dsny isn't it enough to set cni=cilium to get both types of network rules applied?

2024-10-10 14:26 UTC, RVanhuysseXenit commented
We can run it as is, but I think we're setting ourselves up for failure in the future. 
Usage of cilium netpols is not tied to usage of the cilium cni, and using the cilium cni does not mean we want to enable the corresponding netpols immediately.

2024-10-28 08:10 UTC, vierbergenlars approved these changes

2024-10-28 08:14 UTC, vierbergenlars commented
I think the `general.cni` value should be removed completely.

At this point, it only affects if there are cilium network policies enabled or not, and that setting can better be moved to a more explicit `networkPolicies.cilium.enabled`.

The choice of CNI itself should not really affect any other part of the software, only the existence of cilium network policies.

2024-10-28 08:14 UTC, thijslemmens requested changes

2024-10-28 08:14 UTC, thijslemmens commented on README.md
> +#### `general.networkPolicies.cilium.enabled`
how is this different from `general.networkPolicies.enabled` if cni is cilium?
I think this is only disabling the Cilium specific ones? Why would you use cilium as `general.cni` and disable the cilium policies?

2024-11-12 09:06 UTC, closed without merging