OUPDAUNTLE-56 add support for custom alfresco mounts
xenit-eu/helm-alfresco pull request #38
Opened 2023-02-28 14:34 UTC by JoostDeCupere

Also updated the chart to support 3fold image references

2023-03-07 08:46 UTC, thijslemmens requested changes
After discussion:

- mq-deployement.yaml -> mq-deployment.yaml
- make 3-fold image the default and have 'image' override that

2023-03-07 16:43 UTC, thijslemmens requested changes
The `image` documentation needs to be changed. There are no defaults anymore.

2023-03-07 16:43 UTC, thijslemmens commented on README.md
>  * Default: xenit/alfresco-repository-community:7.2.0
default is unset?

2023-03-10 11:48 UTC, thijslemmens approved these changes
@JoostDeCupere Can you check my updates before merging?

2023-03-23 14:23 UTC, hechmi-dammak-xenit commented on xenit-alfresco/values.yaml
> +  registry: 'xenit'
I think this should be docker.io and the repository is xenit/alfresco-repository-community , same for the other ones

2023-03-23 14:24 UTC, hechmi-dammak-xenit commented on xenit-alfresco/values.yaml
> +  registry: 'quay.io/alfresco'
and this is quay.io and the repository is alfresco/alfresco-digital-workspace

2023-03-23 15:53 UTC, hechmi-dammak-xenit requested changes

2023-03-23 15:53 UTC, hechmi-dammak-xenit commented on xenit-alfresco/values.yaml
> +    enabled: false
why is this disabled

2023-03-24 08:38 UTC, hechmi-dammak-xenit approved these changes

2023-03-24 08:48 UTC, merged